# fly.toml app configuration file generated for devtime2 on 2023-09-16T17:49:09-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "devtime2"
primary_region = "gru"
kill_signal = "SIGINT"
kill_timeout = "5s"
console_command = "/app/bin/rails console"

[experimental]
  auto_rollback = true

[build]

[deploy]
  release_command = "bin/rails fly:release"

[env]
  PORT = "3000"

[processes]
  web = "bundle exec puma -C config/puma.rb"
  worker = "bundle exec sidekiq -e production"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["web"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
